### ISSUE TITLE
iconfont不显示

### ISSUE THREAD

**Issue by jineslee** [hqwlkj/DracoApp#5]
嗨，兄弟，你dva里面iconfont不显示的问题怎么解决的？

**Comment by hqwlkj** [comment]
使用 unicode引用，点击复制代码到自己的项目中，再在没每一个 url的括号中，加上http 或者https，这个需要根据你的网站访问协议来定。

修改前：
![image](https://user-images.githubusercontent.com/12181423/33416076-a23c9826-d5d5-11e7-9ff2-79652bb10bdd.png)

修改后：
![image](https://user-images.githubusercontent.com/12181423/33416217-555831b8-d5d6-11e7-9189-4bdac5635ca4.png)


其他的什么都不变，根据 [阿里妈妈MUX矢量图标库](http://iconfont.cn/help/detail?spm=a313x.7781069.1998910419.14&helptype=code) 的帮助文档操作就好了。

**Comment by jineslee** [comment]
OK 多谢！




发自网易邮箱大师
在2017年11月30日 13:57，Yanghc 写道：

使用 unicode引用，点击复制代码到自己的项目中，再在没每一个 url的括号中，加上http 或者https，这个需要根据你的网站访问协议来定。

修改前：


修改后：


其他的什么都不变，根据 阿里妈妈MUX矢量图标库 的帮助文档操作就好了。
